// Turns a chat-drafted garment (buildCustomGarment.js) into a downloadable
// .js file following the exact same shape as src/garments/cap.js. This is a
// SCAFFOLD for a PR, not a finished, mergeable garment - guides/callouts are
// placeholders (see genericSilhouette.js) because a real 4-view silhouette
// and callout coordinates are hand-drawn vector art a chat can't produce.
// The generated file says so explicitly, with a pointer to CONTRIBUTING.md.

function idToCamel(id) {
  return id
    .split("-")
    .map((part, i) => (i === 0 ? part : part.charAt(0).toUpperCase() + part.slice(1)))
    .join("")
}

export function generateGarmentFileText(garment) {
  const varName = idToCamel(garment.id) + "Garment"

  const partsLines = garment.defaultParts.map((p) => `    { id: ${p.id}, val: ${JSON.stringify(p.val)}, on: ${p.on} },`).join("\n")

  const labelEntries = Object.entries(garment.partLabels.ES)
    .map(([id, label]) => `${id}: ${JSON.stringify(label)}`)
    .join(", ")

  const positionEntries = garment.positions.ES.map((p) => JSON.stringify(p)).join(", ")

  return `// Scaffold generated by the "Prenda desde 0" AI chat in TechPack AI Builder.
// This is a STARTING POINT for a pull request, not a finished, mergeable
// garment file: guides/callouts below are placeholders (a generic
// rectangle, no callout pointers) because a real 4-view silhouette with
// callout coordinates is hand-drawn vector art - see CONTRIBUTING.md
// "Adding a new garment type" for what needs to be replaced before this
// can be registered in src/garments/index.js.
${garment.designNotes ? "//\n// Notes from the intake chat about designs/embroidery:\n// " + garment.designNotes.replace(/\n/g, "\n// ") + "\n" : ""}
import { GENERIC_SILHOUETTE } from "./genericSilhouette.js"

export const ${varName} = {
  id: ${JSON.stringify(garment.id)},
  icon: "checkroom",
  label: { ES: ${JSON.stringify(garment.label.ES)}, EN: ${JSON.stringify(garment.label.ES)}, ZH: ${JSON.stringify(garment.label.ES)} },
  // TODO: translate EN/ZH labels above - they're just copies of ES for now.

  defaultParts: [
${partsLines}
  ],

  partLabels: {
    ES: { ${labelEntries} },
    // TODO: EN: { ... }, ZH: { ... } - see cap.js for the expected shape.
    EN: { ${labelEntries} },
    ZH: { ${labelEntries} },
  },

  positions: {
    ES: [${positionEntries}],
    // TODO: EN: [...], ZH: [...]
    EN: [${positionEntries}],
    ZH: [${positionEntries}],
  },

  // TODO: replace with a real hand-drawn 4-view silhouette (front/back/left/
  // right, viewBox 0-200x0-150) and callout coordinates - see cap.js and
  // CONTRIBUTING.md "Adding a new garment type". Placeholder for now:
  guides: [GENERIC_SILHOUETTE, GENERIC_SILHOUETTE, GENERIC_SILHOUETTE, GENERIC_SILHOUETTE],
  callouts: [[], [], [], []],
}
`
}

export function downloadGarmentFile(garment) {
  const text = generateGarmentFileText(garment)
  const blob = new Blob([text], { type: "text/javascript" })
  const url = URL.createObjectURL(blob)
  const a = document.createElement("a")
  a.href = url
  a.download = garment.id + ".js"
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  URL.revokeObjectURL(url)
}
