function part(id, system, label, val) {
  return { id, system, label, val, on: true }
}

export const alpineParkaBenchmark = {
  id: "alpine-parka-benchmark",
  label: "Benchmark completo · Parka alpina modular 3L",
  note: "Proyecto determinista de 40 piezas y tres aplicaciones para probar arquitectura documental, reticula y handoff.",
  documentVersion: "V1/2028",
  approvalStatus: "not-approved",
  hdr: {
    brand: "ATELIER MORFE",
    season: "2028 FW",
    sno: "AM-PK-3L-028",
    cat: "Outerwear tecnico",
    fab: "Nylon 40D 3L, membrana 20K/20K, DWR C0",
    fac: "Portugal",
    ind: "15/03/2028",
    outd: "30/05/2028",
    pname: "Parka Alpina Modular 3L",
  },
  garment: {
    label: { ES: "Parka alpina modular 3L", EN: "Modular alpine 3L parka" },
    benchmark: true,
  },
  parts: [
    part("P01", "shell-body", "Frente izquierdo shell", "Nylon 40D 3L; cortar 1; cinta de sellado 13mm"),
    part("P02", "shell-body", "Frente derecho shell", "Nylon 40D 3L; cortar 1; pieza espejo P01"),
    part("P03", "shell-body", "Espalda central shell", "Nylon 40D 3L; cortar 1 al doblez"),
    part("P04", "shell-body", "Canesu espalda", "Nylon 40D 3L; ventilacion protegida"),
    part("P05", "shell-body", "Panel lateral izquierdo", "Nylon 40D 3L; marcar cintura"),
    part("P06", "shell-body", "Panel lateral derecho", "Nylon 40D 3L; pieza espejo P05"),
    part("P07", "shell-body", "Cinta de sellado shell", "PU 13mm; aplicar en todas las costuras indicadas"),

    part("P08", "hood-neck", "Capucha panel central", "Nylon 40D 3L; cortar 1"),
    part("P09", "hood-neck", "Capucha lateral izquierda", "Nylon 40D 3L; cortar 1"),
    part("P10", "hood-neck", "Capucha lateral derecha", "Nylon 40D 3L; pieza espejo P09"),
    part("P11", "hood-neck", "Visera laminada", "Shell + refuerzo 0.6mm; ancho terminado pendiente"),
    part("P12", "hood-neck", "Cuello interior", "Tricot cepillado 180g; contacto piel"),
    part("P13", "hood-neck", "Base desmontable capucha", "Cinta soporte snaps; correspondencia con escote"),

    part("P14", "sleeves-cuffs", "Manga superior izquierda", "Nylon 40D 3L; manga articulada"),
    part("P15", "sleeves-cuffs", "Manga superior derecha", "Nylon 40D 3L; pieza espejo P14"),
    part("P16", "sleeves-cuffs", "Manga inferior izquierda", "Nylon 40D 3L; incluir ventilacion axilar"),
    part("P17", "sleeves-cuffs", "Manga inferior derecha", "Nylon 40D 3L; pieza espejo P16"),
    part("P18", "sleeves-cuffs", "Refuerzo de codo", "Cordura 160D; borde limpio termosellado"),
    part("P19", "sleeves-cuffs", "Tab de puno", "Hypalon 0.8mm; 55 x 28mm terminado"),

    part("P20", "closures-pockets", "Cierre frontal principal", "YKK Aquaguard Vislon #8, 2-way, 780mm"),
    part("P21", "closures-pockets", "Tapeta interior frontal", "Shell 3L; canal anti-atrapamiento"),
    part("P22", "closures-pockets", "Garage cierre cuello", "Tricot + shell; cubrir cursor cerrado"),
    part("P23", "closures-pockets", "Bolsillo pecho izquierdo", "Cierre Aquaguard #5, 180mm"),
    part("P24", "closures-pockets", "Bolsillo pecho derecho", "Cierre Aquaguard #5, 180mm; espejo P23"),
    part("P25", "closures-pockets", "Bolsillo cargo izquierdo", "Fuelle 35mm; tapa con dos snaps"),
    part("P26", "closures-pockets", "Bolsillo cargo derecho", "Fuelle 35mm; pieza espejo P25"),
    part("P27", "closures-pockets", "Bolsillo interior seguridad", "Malla powernet; cierre coil #3, 160mm"),

    part("P28", "lining-insulation", "Forro frente izquierdo", "Nylon reciclado 20D; acceso de montaje inferior"),
    part("P29", "lining-insulation", "Forro frente derecho", "Nylon reciclado 20D; pieza espejo P28"),
    part("P30", "lining-insulation", "Forro espalda", "Nylon reciclado 20D; cortar 1 al doblez"),
    part("P31", "lining-insulation", "Forro manga izquierda", "Nylon reciclado 20D; cortar 1"),
    part("P32", "lining-insulation", "Forro manga derecha", "Nylon reciclado 20D; pieza espejo P31"),
    part("P33", "lining-insulation", "Aislante torso desmontable", "Primaloft Gold 100g; quilting 100 x 100mm"),
    part("P34", "lining-insulation", "Sistema union forro", "Cierre coil #5 perimetral + snaps en punos"),

    part("P35", "trims-labels", "Cordones capucha", "Poliester 3mm reflectivo; dos salidas frontales"),
    part("P36", "trims-labels", "Toggles capucha", "Acetal negro; 2 unidades"),
    part("P37", "trims-labels", "Cordón dobladillo", "Shock cord 3mm; recorrido completo"),
    part("P38", "trims-labels", "Toggles dobladillo", "Acetal negro; 2 laterales protegidos"),
    part("P39", "trims-labels", "Etiqueta principal y talla", "Damasco 55 x 20mm; centro cuello interior"),
    part("P40", "trims-labels", "Etiqueta cuidado y trazabilidad", "Satin reciclado; costado interior izquierdo"),
  ],
  designs: [
    {
      name: "Logo pecho reflectivo",
      pos: "Pecho izquierdo",
      posDetail: "Centro del arte a 95mm bajo punto alto de hombro y 85mm desde centro frente",
      tec: "Bordado plano con hilo reflectivo; backing hidrosoluble",
      w: 68,
      h: 22,
      fileName: "AM-PK-3L_D1_logo-pecho.dst",
      colors: [
        { name: "Reflective silver", hex: "#C6CBD0" },
        { name: "Black", hex: "#111111" },
      ],
      emb: { machine: "Tajima", needles: 2, stops: 2, stitches: 4800, backing: "Hidrosoluble", stopSeq: [{ stop: 1, name: "Silver", stitches: 3600 }, { stop: 2, name: "Black", stitches: 1200 }] },
      views: ["Colocacion en frente", "Detalle de puntada"],
    },
    {
      name: "Mapa topografico espalda",
      pos: "Canesu y espalda superior",
      posDetail: "Centrado en eje de espalda; borde superior a 42mm bajo costura de canesu",
      tec: "Transfer reflectivo segmentado; aplicar antes del cierre de forro",
      w: 310,
      h: 225,
      fileName: "AM-PK-3L_D2_topo-back.ai",
      colors: [{ name: "Reflective graphite", hex: "#737A80" }],
      views: ["Colocacion espalda", "Cruce con costuras"],
    },
    {
      name: "Parche rescate manga",
      pos: "Manga superior derecha",
      posDetail: "Centro a 145mm bajo punto superior de manga, alineado con linea de hombro",
      tec: "Parche TPU soldado RF; esquinas radio 4mm",
      w: 52,
      h: 74,
      fileName: "AM-PK-3L_D3_rescue-patch.pdf",
      colors: [
        { name: "Signal red", hex: "#E51937" },
        { name: "White", hex: "#FFFFFF" },
        { name: "Black", hex: "#111111" },
      ],
      views: ["Manga completa", "Construccion del parche"],
    },
  ],
}
