function part(id, system, label, material, cut, construction) {
  return {
    id,
    system,
    label,
    val: [material, cut, construction].filter(Boolean).join("; "),
    material,
    cut,
    construction,
    on: true,
  }
}

const parts = [
  part("P01", "waist-fly", "Pretina exterior izquierda", "F01", "Cortar 1", "Une en centro espalda; soporte de correccion de calce"),
  part("P02", "waist-fly", "Pretina exterior derecha", "F01", "Cortar 1", "Espejo funcional de P01"),
  part("P03", "waist-fly", "Pretina interior izquierda", "F04", "Cortar 1", "Contiene elastico lateral sin fruncido exterior"),
  part("P04", "waist-fly", "Pretina interior derecha", "F04", "Cortar 1", "Contiene elastico lateral sin fruncido exterior"),
  part("P05", "waist-fly", "Extension de bragueta", "F01 + F05", "Cortar 1", "Soporte de gancho T08"),
  part("P06", "waist-fly", "Protector interior de cierre", "F01 + F04", "Cortar 1", "Evita contacto del cierre T01"),
  part("P07", "waist-fly", "Tira de trabillas", "F01", "Cortar 1", "Subdividir en 7 trabillas terminadas"),
  part("P08", "waist-fly", "Refuerzo centro espalda", "F04", "Cortar 1", "Soporte para cinta antideslizante"),

  part("P09", "upper-body", "Frente superior izquierdo", "F01", "Cortar 1", "Desde cintura hasta interfaz zip-off"),
  part("P10", "upper-body", "Frente superior derecho", "F01", "Cortar 1", "Espejo estructural de P09"),
  part("P11", "upper-body", "Trasero superior izquierdo", "F01", "Cortar 1", "Volumen athletic en asiento y muslo"),
  part("P12", "upper-body", "Trasero superior derecho", "F01", "Cortar 1", "Espejo estructural de P11"),
  part("P13", "upper-body", "Canesu trasero izquierdo", "F01", "Cortar 1", "Eleva tiro trasero y distribuye volumen"),
  part("P14", "upper-body", "Canesu trasero derecho", "F01", "Cortar 1", "Union en centro espalda"),
  part("P15", "upper-body", "Fuelle de entrepierna", "F01", "Cortar 1", "Diamante; marcar eje de mayor elasticidad"),
  part("P16", "upper-body", "Refuerzo de asiento izquierdo", "F02", "Cortar 1", "Panel integrado, no parche superpuesto"),
  part("P17", "upper-body", "Refuerzo de asiento derecho", "F02", "Cortar 1", "Espejo de P16"),

  part("P18", "pockets", "Vista bolsillo delantero izquierdo", "F01 + F05", "Cortar 1", "Soporta cierre T02 izquierdo"),
  part("P19", "pockets", "Vista bolsillo delantero derecho", "F01 + F05", "Cortar 1", "Soporta cierre T02 derecho"),
  part("P20", "pockets", "Bolsa bolsillo delantero izquierdo", "F03", "Cortar 1", "Anclar a cintura y costado"),
  part("P21", "pockets", "Bolsa bolsillo delantero derecho", "F03", "Cortar 1", "Anclar a cintura y costado"),
  part("P22", "pockets", "Cuerpo cargo izquierdo", "F01", "Cortar 1", "Volumen util para mapa, guantes o gorro"),
  part("P23", "pockets", "Fuelle cargo izquierdo", "F01", "Cortar 1", "Expansion terminada 35 mm"),
  part("P24", "pockets", "Tapa cargo izquierda exterior", "F02 + F05", "Cortar 1", "Recibe bordado D1 antes del montaje"),
  part("P25", "pockets", "Tapa cargo izquierda interior", "F01", "Cortar 1", "Oculta snaps T07"),
  part("P26", "pockets", "Vista superior cargo derecho", "F02 + F05", "Cortar 1", "Forma abertura vertical para T03"),
  part("P27", "pockets", "Vista inferior cargo derecho", "F02 + F05", "Cortar 1", "Forma abertura vertical para T03"),
  part("P28", "pockets", "Bolsa cargo derecho", "F03", "Cortar 1", "Perfil plano para telefono o GPS"),
  part("P29", "pockets", "Vista bolsillo trasero derecho", "F02 + F05", "Cortar 1", "Soporta cierre T04"),
  part("P30", "pockets", "Bolsa bolsillo trasero derecho", "F03", "Cortar 1", "Perfil plano; anclar al canesu"),

  part("P31", "zip-off", "Protector zip-off superior izquierdo", "F01 + F04", "Cortar 1", "Integra garages y cubre espiral T05-L"),
  part("P32", "zip-off", "Protector zip-off superior derecho", "F01 + F04", "Cortar 1", "Integra garages y cubre espiral T05-R"),
  part("P33", "zip-off", "Protector zip-off inferior izquierdo", "F01 + F04", "Cortar 1", "Recibe etiqueta funcional L"),
  part("P34", "zip-off", "Protector zip-off inferior derecho", "F01 + F04", "Cortar 1", "Recibe etiqueta funcional R"),

  part("P35", "lower-leg", "Pierna inferior frente izquierda", "F01", "Cortar 1", "Desde zip-off hasta bajo"),
  part("P36", "lower-leg", "Pierna inferior frente derecha", "F01", "Cortar 1", "Recibe transfer D2 antes de cerrar costado"),
  part("P37", "lower-leg", "Pierna inferior espalda izquierda", "F01", "Cortar 1", "Articulacion posterior de rodilla"),
  part("P38", "lower-leg", "Pierna inferior espalda derecha", "F01", "Cortar 1", "Espejo estructural de P37"),
  part("P39", "lower-leg", "Refuerzo rodilla izquierdo", "F02", "Cortar 1", "Panel integrado con forma prearticulada"),
  part("P40", "lower-leg", "Refuerzo rodilla derecho", "F02", "Cortar 1", "Espejo de P39"),
  part("P41", "lower-leg", "Refuerzo interior bajo izquierdo", "F02", "Cortar 1", "Proteccion contra bota y crampton"),
  part("P42", "lower-leg", "Refuerzo interior bajo derecho", "F02", "Cortar 1", "Espejo de P41"),
  part("P43", "lower-leg", "Vista cierre de bajo izquierda", "F04", "Cortar 1", "Protege cierre T06-L y piel"),
  part("P44", "lower-leg", "Vista cierre de bajo derecha", "F04", "Cortar 1", "Protege cierre T06-R y piel"),
]

export const traverseCargoBenchmark = {
  id: "traverse-cargo-benchmark",
  label: "Benchmark definitivo - Traverse Alpine Zip-Off Cargo",
  note: "Pantalon cargo convertible de trekking alpino; 44 piezas y especificacion textil completa para comparar razonamiento humano y DeepSeek.",
  documentVersion: "V1/2028",
  approvalStatus: "not-approved",
  hdr: {
    brand: "ATELIER MORFE",
    season: "2028 SS",
    sno: "AM-PT-ZO-001",
    cat: "Pantalon tecnico convertible",
    fab: "Nylon stretch double-weave 180 gsm, DWR C0",
    fac: "PENDIENTE DE CONFIRMAR",
    ind: "15/07/2028",
    outd: "PENDIENTE DE CONFIRMAR",
    pname: "Traverse Alpine Zip-Off Cargo",
  },
  garment: {
    label: { ES: "Pantalon cargo alpino convertible", EN: "Convertible alpine cargo pant" },
    benchmark: true,
    audience: "Hombre athletic",
    sizeRange: "28-40",
    baseSize: "34",
    partLabels: { ES: Object.fromEntries(parts.map((item) => [item.id, item.label])) },
  },
  parts,
  designs: [
    {
      id: "D1",
      name: "Wordmark cargo izquierdo",
      pos: "Tapa cargo izquierda P24",
      posDetail: "Centrado horizontalmente; borde inferior a 14 mm del borde terminado de la tapa",
      tec: "Bordado plano antes de montar la tapa; backing hidrosoluble",
      w: 52,
      h: 12,
      fileName: "AM-PT-ZO-001_D1_wordmark.dst",
      views: ["Tapa completa", "Detalle de puntada"],
      colors: [{ name: "Tonal black", hex: "#17191B" }, { name: "Reflective grey", hex: "#BFC5C8" }],
      emb: {
        machine: "Multicabezal industrial",
        needles: 2,
        stops: 2,
        stitches: "PENDIENTE DE DIGITALIZAR",
        backing: "Hidrosoluble; retirar exceso",
        stopSeq: [{ stop: 1, name: "Tonal black", stitches: "PENDIENTE" }, { stop: 2, name: "Reflective grey", stitches: "PENDIENTE" }],
      },
    },
    {
      id: "D2",
      name: "Marcador reflectivo pantorrilla",
      pos: "Pierna inferior frente derecha P36",
      posDetail: "Centrado respecto al panel exterior; borde inferior 85 mm sobre bajo terminado",
      tec: "Transfer segmentado reflectivo; aplicar antes de cerrar costado",
      w: 68,
      h: 22,
      fileName: "AM-PT-ZO-001_D2_reflective-marker.ai",
      views: ["Colocacion pierna derecha", "Detalle de transferencia"],
      colors: [{ name: "Reflective silver", hex: "#C7CDD0" }],
    },
  ],
  humanPagePlan: [
    { page: 1, title: "Portada", purpose: "cover", objective: "Identificar producto, version y estado", pieces: [], views: ["Vista general"] },
    { page: 2, title: "Indice de produccion", purpose: "index", objective: "Navegacion y control de recepcion", pieces: [], views: [] },
    { page: 3, title: "Arquitectura del producto", purpose: "overview", objective: "Explicar modos pantalon/short, materiales y colorways", pieces: [], views: ["Frente pantalon", "Espalda pantalon", "Modo short"] },
    { page: 4, title: "Pretina y bragueta", purpose: "structure:waist-fly", objective: "Construir cierre, ajuste y correccion de calce", pieces: ["P01", "P02", "P03", "P04", "P05", "P06", "P07", "P08"], views: ["Exterior", "Interior abierto", "Bragueta explotada"] },
    { page: 5, title: "Calce del cuerpo superior", purpose: "structure:upper-fit", objective: "Controlar volumen athletic, tiro y centro espalda", pieces: ["P09", "P10", "P11", "P12", "P13", "P14"], views: ["Frente", "Espalda", "Perfil"] },
    { page: 6, title: "Movilidad y refuerzo de asiento", purpose: "structure:mobility", objective: "Explicar fuelle, elasticidad y paneles de asiento", pieces: ["P15", "P16", "P17"], views: ["Entrepierna interior", "Asiento", "Explosion de paneles"] },
    { page: 7, title: "Bolsillos delanteros", purpose: "structure:front-pockets", objective: "Construir acceso bajo mochila y bolsas ancladas", pieces: ["P18", "P19", "P20", "P21"], views: ["Exterior", "Corte transversal", "Interior"] },
    { page: 8, title: "Cargo izquierdo", purpose: "structure:left-cargo", objective: "Construir bolsillo expandible y tapa con snaps", pieces: ["P22", "P23", "P24", "P25"], views: ["Cerrado", "Fuelle abierto", "Tapa interior"] },
    { page: 9, title: "Cargo derecho y bolsillo trasero", purpose: "structure:right-rear-pockets", objective: "Construir bolsillos planos con cierre y anclajes", pieces: ["P26", "P27", "P28", "P29", "P30"], views: ["Cargo derecho", "Bolsillo trasero", "Interior de bolsas"] },
    { page: 10, title: "Sistema convertible zip-off", purpose: "structure:zip-off", objective: "Impedir error L/R y documentar conversion", pieces: ["P31", "P32", "P33", "P34"], views: ["Recorrido de cierre", "Explosion L/R", "Secuencia de conversion"] },
    { page: 11, title: "Piernas inferiores y rodillas", purpose: "structure:lower-leg", objective: "Mantener articulacion y continuidad al montar piernas", pieces: ["P35", "P36", "P37", "P38", "P39", "P40"], views: ["Frente", "Espalda", "Seccion de rodilla"] },
    { page: 12, title: "Bajos y compatibilidad con botas", purpose: "structure:boot-hem", objective: "Retirar pierna sin quitar bota y proteger el bajo", pieces: ["P41", "P42", "P43", "P44"], views: ["Bajo exterior", "Bajo interior", "Secuencia sobre bota"] },
    { page: 13, title: "Medidas y gradacion", purpose: "measurements", objective: "Definir POM, tolerancias y reglas de talla", pieces: [], views: ["Frente acotado", "Espalda acotada"] },
    { page: 14, title: "Mapa de construccion", purpose: "construction", objective: "Relacionar puntadas, margenes, presillas y orden", pieces: [], views: ["Mapa de costuras", "Secciones 301/504/516"] },
    { page: 15, title: "D1 - Wordmark bordado", purpose: "design:Wordmark cargo izquierdo", objective: "Definir colocacion y ejecucion del bordado", pieces: [], views: ["Tapa completa", "Detalle de puntada"] },
    { page: 16, title: "D2 - Marcador reflectivo", purpose: "design:Marcador reflectivo pantorrilla", objective: "Definir colocacion y aplicacion del transfer", pieces: [], views: ["Pierna derecha", "Detalle de transferencia"] },
    { page: 17, title: "Etiquetado y empaque", purpose: "label", objective: "Definir rotulos, marcacion L/R, doblado y bolsa", pieces: [], views: ["Mapa interior", "Secuencia de doblado"] },
    { page: 18, title: "Calidad y pendientes", purpose: "quality", objective: "Controlar pruebas, simetria y bloqueos de aprobacion", pieces: [], views: ["Mapa de inspeccion"] },
  ],
  brief: {
    product: {
      use: "Trekking alpino de varias horas o varios dias, aproximaciones y scrambling ligero",
      user: "Hombre, bloque athletic",
      sizes: [28, 30, 32, 34, 36, 38, 40],
      baseSize: 34,
      protection: "Viento y lluvia ligera; no impermeable",
      transformation: "Piernas desmontables sobre rodilla; conversion sin quitar botas",
      priorities: ["libertad de zancada", "abrasion", "secado rapido", "bolsillos accesibles con mochila", "montaje L/R sin error"],
    },
    materials: [
      { id: "F01", name: "Double-weave principal", spec: "90% nylon / 10% elastano; 180 gsm; 4-way stretch; DWR C0; ancho util pendiente" },
      { id: "F02", name: "Nylon 6.6 high-tenacity stretch", spec: "93% nylon / 7% elastano; 235 gsm; acabado DWR C0" },
      { id: "F03", name: "Malla de bolsillo", spec: "100% poliester reciclado; 110 gsm" },
      { id: "F04", name: "Tricot cepillado", spec: "100% poliester; 125 gsm; contacto suave" },
      { id: "F05", name: "Entretela fusible ligera", spec: "Poliamida; 40 gsm; validar adhesion y recuperacion" },
    ],
    trims: [
      { id: "T01", spec: "Cierre bragueta coil #5; cursor autoblocante; 1" },
      { id: "T02", spec: "Cierres bolsillos delanteros reverse-coil #3; 2" },
      { id: "T03", spec: "Cierre cargo derecho reverse-coil #3; 1" },
      { id: "T04", spec: "Cierre bolsillo trasero reverse-coil #3; 1" },
      { id: "T05-L/R", spec: "Cierres zip-off separables reverse-coil #5; diferenciados por pierna; 1 par" },
      { id: "T06-L/R", spec: "Cierres de bajo reverse-coil #5; apertura desde bajo; 1 par" },
      { id: "T07", spec: "Snaps ocultos 12 mm negro mate; 2" },
      { id: "T08", spec: "Gancho de pretina metalico plano negro; 1" },
      { id: "T09", spec: "Boton interior poliester 18L; 1" },
      { id: "T10", spec: "Elastico pretina 35 mm alta recuperacion; 2 tramos" },
      { id: "T11", spec: "Shock cord reflectivo poliester 3 mm; 2 tramos" },
      { id: "T12", spec: "Toggles acetal perfil bajo; 2" },
      { id: "T13", spec: "Ganchos de bota acetal reforzado ocultables; 2" },
      { id: "T14", spec: "Hilo principal poliester core-spun Tex 40" },
      { id: "T15", spec: "Hilo refuerzo poliester core-spun Tex 60" },
      { id: "T16", spec: "Etiquetas tejidas L/R; rojo izquierda, azul derecha; 1 par" },
      { id: "T17", spec: "Etiqueta principal/talla damasco reciclado; 1" },
      { id: "T18", spec: "Care/content label satin reciclado con trazabilidad; 1" },
    ],
    colorways: [
      { id: "CW01 BASALT", F01: "Graphite #3E4448", F02: "Black #17191B", trims: "Negro mate", thread: "Tono sobre tono" },
      { id: "CW02 ALPINE MOSS", F01: "Moss #56604A", F02: "Dark Olive #272D25", trims: "Negro mate", thread: "Tono sobre tono" },
    ],
    construction: {
      seams: [
        "General: puntada 301, 10 mm de margen, 4 puntadas/cm",
        "Tiro e entrepierna: safety stitch 516, margen 12 mm, refuerzo Tex 60",
        "Bordes internos restantes: overlock 504, sin orillas expuestas",
        "Pespunte de asentamiento: 301 a 2.5 mm donde se indique",
        "Bolsillos y tapas: margen 8 mm; esquinas con radio, no picos internos",
        "Canal de bajo: retorno 25 mm con acceso protegido al shock cord",
      ],
      bartacks: ["Extremos de cada abertura", "Trabillas", "Fuelle cargo", "Inicio/fin T05 y T06", "Gancho de bota"],
      criticalOrder: [
        "Aplicar D1 sobre P24 y D2 sobre P36 antes de ensamblar",
        "Construir bolsas y vistas antes de cerrar costados",
        "Montar protectores P31-P34 y verificar L/R antes de cerrar pierna",
        "Cerrar refuerzos de rodilla y asiento como paneles integrados",
        "Instalar pretina despues de validar bragueta, bolsillos y centro espalda",
      ],
    },
    measurements: {
      units: "cm",
      baseSize: 34,
      poms: [
        { id: "M01", name: "Cintura relajada 1/2", value: 43.2, tolerance: 0.5 },
        { id: "M02", name: "Cintura extendida 1/2", value: 46.0, tolerance: 0.7 },
        { id: "M03", name: "Cadera 1/2 a 20 cm bajo cintura", value: 56.0, tolerance: 1.0 },
        { id: "M04", name: "Tiro delantero incluido pretina", value: 28.0, tolerance: 0.7 },
        { id: "M05", name: "Tiro trasero incluido pretina", value: 39.5, tolerance: 0.7 },
        { id: "M06", name: "Muslo 1/2 a 2.5 cm de entrepierna", value: 34.5, tolerance: 0.7 },
        { id: "M07", name: "Rodilla 1/2", value: 23.5, tolerance: 0.5 },
        { id: "M08", name: "Bajo 1/2 relajado", value: 19.5, tolerance: 0.5 },
        { id: "M09", name: "Entrepierna modo pantalon", value: 81.0, tolerance: 1.0 },
        { id: "M10", name: "Entrepierna modo short", value: 28.0, tolerance: 0.7 },
        { id: "M11", name: "Largo costado incluido pretina", value: 108.0, tolerance: 1.0 },
        { id: "M12", name: "Alto pretina terminado", value: 4.2, tolerance: 0.2 },
        { id: "M13", name: "Abertura bolsillo delantero", value: 17.5, tolerance: 0.3 },
        { id: "M14", name: "Cargo izquierdo terminado ancho x alto x fuelle", value: "19 x 17 x 3.5", tolerance: 0.3 },
        { id: "M15", name: "Abertura cargo derecho", value: 18.0, tolerance: 0.3 },
        { id: "M16", name: "Largo cierre de bajo", value: 32.0, tolerance: 0.3 },
      ],
      grading: [
        "Tallas en saltos de 2 pulgadas: 28-40",
        "Cintura 1/2: +/-2.5 cm por talla",
        "Cadera 1/2: +/-1.5 cm por talla",
        "Tiro delantero/trasero: +/-0.5 cm por talla",
        "Muslo 1/2: +/-0.8 cm por talla; rodilla y bajo 1/2: +/-0.5 cm",
        "Entrepierna constante; validar largos short y posicion T05 en todas las tallas",
      ],
      status: "Valores de desarrollo para primera muestra; requieren validacion de patron y fitting",
    },
    labelsAndPackaging: {
      labels: [
        "T17 centrada en pretina interior trasera; talla visible sin voltear prenda",
        "T18 en costado interior izquierdo, bajo bolsa de bolsillo y sin interferir con T05-L",
        "T16-L roja en P33 y T16-R azul en P34; invisibles con piernas montadas",
        "Contenido: 90% nylon / 10% elastano para shell; declarar refuerzo por separado segun normativa",
        "Origen y simbolos de cuidado pendientes de fabrica y pruebas de laboratorio",
      ],
      pack: [
        "Entregar con piernas montadas y cierres T05 cerrados",
        "Shock cords relajados; cursores protegidos por garages",
        "Doblar en tercios sin comprimir tapas cargo",
        "Una bolsa reciclada por unidad con sticker style/color/talla y advertencia legal",
        "Incluir tarjeta pequena de conversion L/R; contenido final pendiente de aprobacion",
      ],
    },
    quality: [
      "Verificar que pierna izquierda no pueda montarse en lado derecho y viceversa",
      "50 ciclos completos de T05 y T06 sin atasco, separacion de cinta ni deformacion",
      "Simetria de lineas zip-off, rodillas, cargos y bajos: diferencia maxima 5 mm",
      "Prueba de recuperacion elastica y crecimiento en rodilla/asiento tras uso simulado",
      "Abrasion comparativa F01/F02 y resistencia de presillas en bolsillos y trabillas",
      "Spray test DWR inicial y despues de 5 lavados; no declarar impermeabilidad",
      "Adhesion y elasticidad de D2; bordado D1 sin puckering ni backing rigido",
      "Medidas dentro de tolerancia despues de acondicionamiento 24 h",
    ],
    openPoints: [
      "Proveedor y ancho util de F01-F05",
      "Longitudes exactas de T01-T06 por talla despues de patron",
      "Consumos y marcadas",
      "Numero de puntadas final de D1 despues de digitalizacion",
      "Parametros de prensa para D2 despues de prueba de adhesion",
      "Pais de origen, fabrica, fecha de salida y simbologia legal de cuidado",
      "Aprobacion de fitting, muestra de talla, color y pruebas de laboratorio",
    ],
  },
}
