// Madeira Classic Rayon No.40 color numbers and names, transcribed from
// Madeira USA's own official reference PDF ("Classic colornames2015.pdf",
// madeirausa.com/resources/). Madeira's own cover note on that document:
// "Color names are for your reference only. When ordering please refer to
// each color by color number." - the number is the source of truth, the
// name is decorative. Everything here follows that rule.
export const MADEIRA_CLASSIC_RAYON = [
  { code: "1000", name: "Emerald Black" },
  { code: "1001", name: "Super White" },
  { code: "1002", name: "Snow White" },
  { code: "1003", name: "Cream White" },
  { code: "1004", name: "Natural White" },
  { code: "1005", name: "Fluorescent White" },
  { code: "1006", name: "Diamond Black" },
  { code: "1007", name: "Amber Black" },
  { code: "1008", name: "Ruby Black" },
  { code: "1009", name: "Sapphire Black" },
  { code: "1010", name: "Gray Haze" },
  { code: "1011", name: "Chrome" },
  { code: "1012", name: "Smoke" },
  { code: "1013", name: "Peach Blush" },
  { code: "1014", name: "Bermuda Sand" },
  { code: "1015", name: "Desert Bloom" },
  { code: "1017", name: "Orange Wisp" },
  { code: "1018", name: "Light Salmon" },
  { code: "1020", name: "Bright Peach" },
  { code: "1021", name: "Rust" },
  { code: "1022", name: "Corn Silk" },
  { code: "1023", name: "Lemon" },
  { code: "1024", name: "Gold Rush" },
  { code: "1025", name: "Military Gold" },
  { code: "1026", name: "Orange Sorbet" },
  { code: "1027", name: "Dolphin" },
  { code: "1028", name: "Country Kitchen Blue" },
  { code: "1029", name: "Blue Jay" },
  { code: "1030", name: "Light Periwinkle" },
  { code: "1031", name: "Frosted Lavender" },
  { code: "1032", name: "Velvet Violet" },
  { code: "1033", name: "Purple Pansy" },
  { code: "1034", name: "Vintage Rose" },
  { code: "1035", name: "Burgundy" },
  { code: "1036", name: "Raisin" },
  { code: "1037", name: "Tango" },
  { code: "1038", name: "Barn Red" },
  { code: "1039", name: "Brick Red" },
  { code: "1040", name: "Weimaraner" },
  { code: "1041", name: "Polished Pewter" },
  { code: "1042", name: "Lapis" },
  { code: "1043", name: "Navy" },
  { code: "1044", name: "Indigo" },
  { code: "1045", name: "Light Mint" },
  { code: "1046", name: "Eucalyptus" },
  { code: "1047", name: "Celadon" },
  { code: "1048", name: "Aloe" },
  { code: "1049", name: "Lime Green" },
  { code: "1050", name: "Green Thumb" },
  { code: "1051", name: "Bell Pepper" },
  { code: "1052", name: "Mermaid" },
  { code: "1053", name: "Light Coral" },
  { code: "1054", name: "Tawny" },
  { code: "1055", name: "Latte" },
  { code: "1056", name: "Golden Oak" },
  { code: "1057", name: "Caramel" },
  { code: "1058", name: "Sienna" },
  { code: "1059", name: "Dark Chocolate" },
  { code: "1060", name: "Pussywillow" },
  { code: "1061", name: "Vanilla Pudding" },
  { code: "1064", name: "Goldenrod" },
  { code: "1065", name: "Copper" },
  { code: "1066", name: "Cornmeal" },
  { code: "1067", name: "Lemon Chiffon" },
  { code: "1068", name: "Canary" },
  { code: "1069", name: "Sunshine Yellow" },
  { code: "1070", name: "Tawny Tan" },
  { code: "1071", name: "Baby's Breath" },
  { code: "1072", name: "Coconut Cream" },
  { code: "1074", name: "Powder Blue" },
  { code: "1075", name: "Baby Blue" },
  { code: "1076", name: "True Blue" },
  { code: "1078", name: "Pumpkin" },
  { code: "1079", name: "Celtic Green" },
  { code: "1080", name: "Lilac" },
  { code: "1081", name: "Azalea" },
  { code: "1082", name: "Antique Ecru" },
  { code: "1083", name: "Daisy" },
  { code: "1084", name: "Sandy Shores" },
  { code: "1085", name: "Cement" },
  { code: "1086", name: "Sterling Silver" },
  { code: "1087", name: "Silver Birch" },
  { code: "1088", name: "Robin's Egg" },
  { code: "1089", name: "Sea Frost" },
  { code: "1090", name: "Deep Sky Blue" },
  { code: "1091", name: "Teal Blue" },
  { code: "1092", name: "Summer Sky" },
  { code: "1093", name: "Azure Sea" },
  { code: "1094", name: "Caribbean Blue" },
  { code: "1095", name: "Larimar" },
  { code: "1096", name: "Cobalt" },
  { code: "1097", name: "Honeydew Melon" },
  { code: "1098", name: "Blue Grass" },
  { code: "1099", name: "Leek" },
  { code: "1100", name: "Cucumber" },
  { code: "1101", name: "Wintergreen" },
  { code: "1102", name: "Light Moss Green" },
  { code: "1103", name: "Hunter Green" },
  { code: "1104", name: "Scallion" },
  { code: "1105", name: "Weeping Willow" },
  { code: "1106", name: "Guacamole" },
  { code: "1107", name: "Honeysuckle" },
  { code: "1108", name: "Pink Carnation" },
  { code: "1109", name: "Pink Rose" },
  { code: "1110", name: "Fuchsia" },
  { code: "1111", name: "Evening Mist" },
  { code: "1112", name: "Majestic Purple" },
  { code: "1114", name: "Pink Petal" },
  { code: "1115", name: "Powder Puff" },
  { code: "1116", name: "Cotton Candy" },
  { code: "1117", name: "Flamingo Pink" },
  { code: "1118", name: "Overcast Gray" },
  { code: "1119", name: "English Rose" },
  { code: "1120", name: "Baby Pink" },
  { code: "1121", name: "Candy Heart" },
  { code: "1122", name: "Deep Lilac" },
  { code: "1123", name: "Parchment" },
  { code: "1124", name: "Buttercup" },
  { code: "1125", name: "Saffron" },
  { code: "1126", name: "Light Brown Sugar" },
  { code: "1127", name: "Loofah" },
  { code: "1128", name: "Taupe" },
  { code: "1129", name: "Mud Pie" },
  { code: "1130", name: "Chocolate Chip" },
  { code: "1131", name: "Espresso" },
  { code: "1132", name: "Clear Blue" },
  { code: "1133", name: "Forget-Me-Not" },
  { code: "1134", name: "Royal Blue" },
  { code: "1135", name: "Baby Chick" },
  { code: "1136", name: "Dark Taupe" },
  { code: "1137", name: "Citrus Burst" },
  { code: "1138", name: "Doe Skin" },
  { code: "1140", name: "Avocado Green" },
  { code: "1141", name: "Mauve" },
  { code: "1142", name: "Peach Puff" },
  { code: "1143", name: "China Blue" },
  { code: "1144", name: "Bark" },
  { code: "1145", name: "Coffee Bean" },
  { code: "1146", name: "Tomato Red" },
  { code: "1147", name: "Christmas Red" },
  { code: "1148", name: "Rustic Pink" },
  { code: "1149", name: "Tusk" },
  { code: "1150", name: "Chartreuse" },
  { code: "1151", name: "Silver Moon" },
  { code: "1152", name: "Peach Tea" },
  { code: "1153", name: "Frosted Glass" },
  { code: "1154", name: "Lipstick Rose" },
  { code: "1155", name: "Marmalade" },
  { code: "1156", name: "Palm Frond" },
  { code: "1157", name: "Marsh" },
  { code: "1158", name: "Chestnut" },
  { code: "1159", name: "Mustard" },
  { code: "1160", name: "Antique Blue" },
  { code: "1161", name: "Twilight" },
  { code: "1162", name: "Admiral Blue" },
  { code: "1163", name: "Steel Green" },
  { code: "1164", name: "Twister" },
  { code: "1166", name: "Hanukkah Blue" },
  { code: "1167", name: "Blue Ink" },
  { code: "1169", name: "Split Pea" },
  { code: "1170", name: "Fern" },
  { code: "1171", name: "Lemon Drop" },
  { code: "1172", name: "Egg Yolk" },
  { code: "1173", name: "Autumn Gold" },
  { code: "1174", name: "Cinnamon Stick" },
  { code: "1175", name: "Dark Federal Blue" },
  { code: "1176", name: "Navajo Blue" },
  { code: "1177", name: "Blue Bird" },
  { code: "1178", name: "Carrot" },
  { code: "1179", name: "Sweet Potato" },
  { code: "1180", name: "Daffodil" },
  { code: "1181", name: "Candy Apple Red" },
  { code: "1182", name: "Mulberry" },
  { code: "1183", name: "Cranberry" },
  { code: "1184", name: "Scarlet Rose" },
  { code: "1185", name: "Dark Teal" },
  { code: "1186", name: "Ruby Slipper" },
  { code: "1187", name: "Orchid" },
  { code: "1188", name: "Chokecherry" },
  { code: "1189", name: "Moss Green" },
  { code: "1190", name: "Sea Weed" },
  { code: "1191", name: "Gold Coin" },
  { code: "1192", name: "Honey Mustard" },
  { code: "1193", name: "Peridot" },
  { code: "1194", name: "Dark Olive" },
  { code: "1195", name: "Menthol" },
  { code: "1196", name: "Medium Camo Green" },
  { code: "1198", name: "Moonstone" },
  { code: "1199", name: "Onyx" },
  { code: "1212", name: "Stainless Steel" },
  { code: "1219", name: "Hint of Mint" },
  { code: "1220", name: "Conch Shell" },
  { code: "1221", name: "Terra Cotta" },
  { code: "1223", name: "Lemon Tart" },
  { code: "1224", name: "Lemonade" },
  { code: "1225", name: "Liquid Gold" },
  { code: "1226", name: "Amber" },
  { code: "1227", name: "Mint Jubilee" },
  { code: "1228", name: "Mink" },
  { code: "1229", name: "Clove" },
  { code: "1230", name: "Root Beer" },
  { code: "1232", name: "Lavender" },
  { code: "1233", name: "Blackberry Purple" },
  { code: "1234", name: "Hibiscus" },
  { code: "1235", name: "Crocus" },
  { code: "1236", name: "Plum Brandy" },
  { code: "1238", name: "Sangria" },
  { code: "1239", name: "Charcoal" },
  { code: "1240", name: "Stone" },
  { code: "1241", name: "Obsidian" },
  { code: "1242", name: "Dark Denim" },
  { code: "1243", name: "Star-kissed Night" },
  { code: "1244", name: "Darkest Night" },
  { code: "1245", name: "Sea Foam Green" },
  { code: "1246", name: "Teal Green" },
  { code: "1247", name: "Bottle Green" },
  { code: "1248", name: "Margarita Lime" },
  { code: "1249", name: "Shamrock" },
  { code: "1250", name: "Christmas Green" },
  { code: "1251", name: "Kelly Green" },
  { code: "1252", name: "Neptune" },
  { code: "1253", name: "Penny" },
  { code: "1254", name: "Dark Salmon" },
  { code: "1255", name: "Khaki" },
  { code: "1256", name: "Teddy Bear" },
  { code: "1257", name: "Bronze" },
  { code: "1258", name: "Grizzley Bear" },
  { code: "1259", name: "Cocoa" },
  { code: "1260", name: "Canvas" },
  { code: "1261", name: "Lavendula" },
  { code: "1263", name: "Dusty Lilac" },
  { code: "1264", name: "Lavender Ice" },
  { code: "1266", name: "Regal Blue" },
  { code: "1270", name: "Sawdust" },
  { code: "1272", name: "Golden Retriever" },
  { code: "1273", name: "Peanut Brittle" },
  { code: "1274", name: "Porcelain Blue" },
  { code: "1275", name: "Periwinkle" },
  { code: "1276", name: "Light Denim" },
  { code: "1277", name: "Blueberry Smash" },
  { code: "1278", name: "Orange Icing" },
  { code: "1279", name: "Tropical Teal" },
  { code: "1280", name: "Oregon Green" },
  { code: "1281", name: "Radish" },
  { code: "1284", name: "Emerald Sea" },
  { code: "1286", name: "Mist" },
  { code: "1287", name: "Gun Metal" },
  { code: "1288", name: "Shark" },
  { code: "1289", name: "Silver Mound" },
  { code: "1290", name: "Mallard Teal" },
  { code: "1291", name: "Marlin" },
  { code: "1292", name: "Limestone" },
  { code: "1293", name: "Malachite" },
  { code: "1294", name: "Liberty" },
  { code: "1295", name: "Cyan" },
  { code: "1296", name: "Deep Ocean" },
  { code: "1297", name: "Calypso Blue" },
  { code: "1298", name: "Tree Frog" },
  { code: "1299", name: "Green Turquoise" },
  { code: "1301", name: "Jade" },
  { code: "1302", name: "Spearmint" },
  { code: "1303", name: "Fresh Oregano" },
  { code: "1304", name: "Ivy" },
  { code: "1305", name: "Chamois" },
  { code: "1306", name: "Army Green" },
  { code: "1307", name: "Raspberry Punch" },
  { code: "1308", name: "Army Fatigues" },
  { code: "1309", name: "Dahlia" },
  { code: "1310", name: "Magenta" },
  { code: "1311", name: "Mystic Lavender" },
  { code: "1312", name: "Purple Grape" },
  { code: "1313", name: "Berry Blast" },
  { code: "1315", name: "Pink Grapefruit" },
  { code: "1317", name: "Blush Pink" },
  { code: "1318", name: "Graphite" },
  { code: "1319", name: "Iris" },
  { code: "1320", name: "Purple Heart" },
  { code: "1321", name: "Bubble Gum Pink" },
  { code: "1322", name: "Royal Purple" },
  { code: "1323", name: "Golden Wheat" },
  { code: "1328", name: "Buckskin" },
  { code: "1329", name: "Toasted Marshmellow" },
  { code: "1330", name: "Bahamas Blue" },
  { code: "1334", name: "Purple Passion" },
  { code: "1335", name: "Dark Periwinkle" },
  { code: "1336", name: "Saddle Brown" },
  { code: "1337", name: "Gray Mist" },
  { code: "1338", name: "Nutmeg" },
  { code: "1339", name: "Spanish Moss" },
  { code: "1342", name: "Fawn" },
  { code: "1343", name: "Grape Juice" },
  { code: "1344", name: "Camel" },
  { code: "1348", name: "Antique Bronze" },
  { code: "1349", name: "Palomino" },
  { code: "1350", name: "Citrus Green" },
  { code: "1351", name: "Alligator" },
  { code: "1352", name: "Old Gold" },
  { code: "1353", name: "Blue Spruce" },
  { code: "1354", name: "Watermelon" },
  { code: "1356", name: "Pink Pearl" },
  { code: "1357", name: "Dark Seaweed" },
  { code: "1358", name: "Cedar Bark" },
  { code: "1359", name: "Golden Nugget" },
  { code: "1360", name: "Dusty Blue" },
  { code: "1361", name: "Moody Gray" },
  { code: "1362", name: "Slate Purple" },
  { code: "1363", name: "Steel Lavender" },
  { code: "1364", name: "Storm Sky Blue" },
  { code: "1365", name: "Dusty Plum" },
  { code: "1366", name: "Dark Purple Iris" },
  { code: "1367", name: "Black Pearl" },
  { code: "1368", name: "Night Sky" },
  { code: "1369", name: "Fresh Pine" },
  { code: "1370", name: "Fir" },
  { code: "1371", name: "Deep Sea" },
  { code: "1372", name: "Honey" },
  { code: "1373", name: "Cerulean Frost" },
  { code: "1374", name: "Maroon" },
  { code: "1375", name: "Work Shirt" },
  { code: "1376", name: "Space Blue" },
  { code: "1377", name: "Kiwi" },
  { code: "1378", name: "Paprika" },
  { code: "1379", name: "Mandarin" },
  { code: "1380", name: "Oasis" },
  { code: "1381", name: "Ripe Raspberry" },
  { code: "1382", name: "Colonial Rose" },
  { code: "1383", name: "Pink Pansy" },
  { code: "1384", name: "Merlot" },
  { code: "1385", name: "Garnet" },
  { code: "1386", name: "Eggplant" },
  { code: "1387", name: "Berry Frost" },
  { code: "1388", name: "Plum" },
  { code: "1389", name: "Bordeaux" },
  { code: "1390", name: "Forest Green" },
  { code: "1391", name: "Spruce Green" },
  { code: "1392", name: "Silver Sage" },
  { code: "1393", name: "Bass Green" },
  { code: "1394", name: "Kale" },
  { code: "1395", name: "Rosemary" },
  { code: "1396", name: "Dark Sage" },
  { code: "1397", name: "Evergreen" },
  { code: "1405", name: "Goose Gray" },
  { code: "1406", name: "Dark Camo Green" },
  { code: "1410", name: "Ivory" },
  { code: "1411", name: "Silver" },
  { code: "1412", name: "Violet" },
  { code: "1415", name: "Battleship" },
  { code: "1421", name: "Basket Ball" },
  { code: "1422", name: "African Violet" },
  { code: "1425", name: "Pumpkin Spice" },
  { code: "1428", name: "Rice" },
  { code: "1430", name: "Dusky Mauve" },
  { code: "1431", name: "Bittersweet Chocolate" },
  { code: "1432", name: "Little Boy Blue" },
  { code: "1434", name: "French Blue" },
  { code: "1437", name: "Summer Sun" },
  { code: "1439", name: "Ash" },
  { code: "1440", name: "Cobblestone" },
  { code: "1445", name: "Cappuccino" },
  { code: "1447", name: "Cinnamon Candy" },
  { code: "1448", name: "Julep" },
  { code: "1449", name: "Key Lime" },
  { code: "1450", name: "Electric Lime" },
  { code: "1451", name: "Celery" },
  { code: "1460", name: "Ecru" },
  { code: "1461", name: "Iron Gray" },
  { code: "1463", name: "Willow" },
  { code: "1466", name: "Sailor Blue" },
  { code: "1467", name: "Pea Coat" },
  { code: "1469", name: "Granny Smith" },
  { code: "1470", name: "Vegas Gold" },
  { code: "1476", name: "Independence Blue" },
  { code: "1477", name: "Salsa" },
  { code: "1478", name: "Orange Peel" },
  { code: "1479", name: "Emerald Isle" },
  { code: "1480", name: "Rain Forest" },
  { code: "1481", name: "Cherry Pie" },
  { code: "1484", name: "Rhubarb" },
  { code: "1485", name: "Electric Red" },
  { code: "1488", name: "Dark Magenta" },
  { code: "1489", name: "Clover" },
  { code: "1491", name: "Brass" },
  { code: "1494", name: "Olive Green" },
  { code: "1495", name: "Safari" },
  { code: "1497", name: "Peacock Blue" },
]

const BY_CODE = new Map(MADEIRA_CLASSIC_RAYON.map((t) => [t.code, t]))
const BY_NAME = new Map(MADEIRA_CLASSIC_RAYON.map((t) => [t.name.toLowerCase(), t]))

// Looks up a color strictly by its 4-digit thread number - the only
// identifier Madeira itself considers authoritative for ordering.
export function findMadeiraThreadByCode(code) {
  const digits = String(code || "").match(/\d{4}/)
  return (digits && BY_CODE.get(digits[0])) || null
}

// Exact (case-insensitive) name lookup - deliberately NOT fuzzy, since an
// auto-applied wrong match here means a factory could be told to order the
// wrong spool. Fuzzy matching belongs in the UI (searchMadeiraThreads),
// where a person picks the result, not in code that writes silently.
export function findMadeiraThreadByName(name) {
  const key = String(name || "").trim().toLowerCase()
  return (key && BY_NAME.get(key)) || null
}

// Free-text search for a picker/autocomplete UI - matches on code prefix or
// name substring, most relevant first. Returns candidates for a HUMAN to
// choose from; never used to silently overwrite data (see
// canonicalizeStopSeq below, which only trusts exact matches).
export function searchMadeiraThreads(query, limit = 12) {
  const q = String(query || "").trim().toLowerCase()
  if (!q) return []
  const starts = []
  const contains = []
  for (const t of MADEIRA_CLASSIC_RAYON) {
    const name = t.name.toLowerCase()
    if (t.code.startsWith(q) || name.startsWith(q)) starts.push(t)
    else if (name.includes(q)) contains.push(t)
  }
  return [...starts, ...contains].slice(0, limit)
}

// Reconciles a Wilcom-extracted stopSeq against the official Madeira chart.
// Wilcom worksheets already state a thread code and/or name per stop - this
// trusts the CODE (the only field Madeira itself calls authoritative) and
// replaces the name with the catalog's official one whenever it differs, so
// a mistyped or outdated name in the source document doesn't survive into
// the ficha. When only a name is present (no code, or an unrecognized one),
// a name match is used just to backfill the missing code - never the reverse:
// a code always wins over whatever name came with it.
//
// Returns { stopSeq, corrections } - corrections is a flat list of what
// changed and why, for the UI to show instead of silently rewriting data
// the person can't see (this is exactly how a doc claiming "1055 = Old
// Gold" was caught: Madeira's own chart says 1055 is "Latte").
export function canonicalizeStopSeq(stopSeq) {
  const list = Array.isArray(stopSeq) ? stopSeq : []
  const corrections = []
  const canonicalized = list.map((stop, i) => {
    if (!stop || typeof stop !== "object") return stop
    const byCode = findMadeiraThreadByCode(stop.code) || findMadeiraThreadByCode(stop.name)
    const match = byCode || findMadeiraThreadByName(stop.name)
    if (!match) return stop
    const extractedName = String(stop.name || "").trim()
    if (match.code !== String(stop.code || "").trim() || match.name !== extractedName) {
      corrections.push({
        stop: stop.stop != null ? stop.stop : i + 1,
        extractedCode: stop.code || "",
        extractedName: extractedName || "",
        officialCode: match.code,
        officialName: match.name,
      })
    }
    return { ...stop, code: match.code, name: match.name }
  })
  return { stopSeq: canonicalized, corrections }
}
